import json
import os

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

_client = Groq(api_key=os.environ["GROQ_API_KEY"])

_SYSTEM_PROMPT = """You are a text provenance classifier. Given a piece of text, assess \
whether it was written by a human or generated by an AI language model.

Consider semantic coherence, stylistic consistency, naturalness of phrasing, and whether \
the text "reads" like AI output (e.g. formulaic transitions, suspiciously balanced \
arguments, overly uniform paragraph structure).

Respond with ONLY a JSON object in this exact format, no other text:
{"ai_probability": <float between 0.0 and 1.0, higher = more likely AI-generated>, "reasoning": "<one sentence explanation>"}
"""


def llm_signal(text):
    response = _client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
        temperature=0,
        response_format={"type": "json_object"},
    )

    result = json.loads(response.choices[0].message.content)

    return {
        "ai_probability": float(result["ai_probability"]),
        "reasoning": result["reasoning"],
    }


if __name__ == "__main__":
    test_inputs = [
        "In conclusion, it is important to note that the aforementioned factors collectively "
        "contribute to a comprehensive understanding of the subject matter at hand. "
        "Furthermore, these considerations underscore the significance of a balanced approach.",
        "honestly idk why but today just felt off, like i woke up and my coffee tasted "
        "weird and then i missed the bus and just spent the whole day kind of annoyed lol",
        "The cat sat on the windowsill, tail flicking, watching rain streak down the glass.",
    ]

    for text in test_inputs:
        print(text[:60] + "...")
        print(llm_signal(text))
        print()
