import json
import os
import re
import statistics

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

_client = Groq(api_key=os.environ["GROQ_API_KEY"])

_SYSTEM_PROMPT = """You are a text provenance classifier. Given a piece of text, assess \
whether it was written by a human or generated by an AI language model.

Consider semantic coherence, stylistic consistency, naturalness of phrasing, and whether \
the text "reads" like AI output (e.g. formulaic transitions, suspiciously balanced \
arguments, overly uniform paragraph structure).

Respond with ONLY a JSON object in this exact format, no other text:
{"ai_probability": <float between 0.0 and 1.0, higher = more likely AI-generated>, "reasoning": "<one sentence explanation>"}
"""


def llm_signal(text):
    response = _client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
        temperature=0,
        response_format={"type": "json_object"},
    )

    result = json.loads(response.choices[0].message.content)

    return {
        "ai_probability": float(result["ai_probability"]),
        "reasoning": result["reasoning"],
    }


def _clamp(value, low=0.0, high=1.0):
    return max(low, min(high, value))


def stylo_signal(text):
    paragraphs = [p for p in re.split(r"\n\s*\n", text.strip()) if p.strip()] or [text.strip()]
    sentences = [s for s in re.split(r"(?<=[.!?])\s+", text.strip()) if s.strip()]
    words = re.findall(r"[A-Za-z']+", text)

    sentence_lengths = [len(re.findall(r"[A-Za-z']+", s)) for s in sentences]

    # 1. Sentence length variance: low variance (low coefficient of variation) = AI-like.
    if len(sentence_lengths) >= 2 and statistics.mean(sentence_lengths) > 0:
        cv = statistics.stdev(sentence_lengths) / statistics.mean(sentence_lengths)
        sentence_variance_score = _clamp(1 - cv)
    else:
        sentence_variance_score = 0.5  # not enough sentences to measure

    # 2. Type-token ratio: lower diversity = AI-like.
    if words:
        ttr = len(set(w.lower() for w in words)) / len(words)
        ttr_score = _clamp(1 - ttr)
    else:
        ttr_score = 0.5

    # 3. Punctuation density: sparse/regular punctuation = AI-like.
    punct_chars = len(re.findall(r"[.,;:!?\"'()\-]", text))
    punct_density = punct_chars / len(text) if text else 0
    punct_score = _clamp(1 - min(punct_density / 0.08, 1))

    # 4. Average word length: slightly higher = AI-like.
    if words:
        avg_word_len = sum(len(w) for w in words) / len(words)
        word_len_score = _clamp((avg_word_len - 3) / 4)
    else:
        word_len_score = 0.5

    # 5. Paragraph/sentence regularity: very even sentences-per-paragraph = AI-like.
    if len(paragraphs) >= 2:
        sentences_per_paragraph = [
            len([s for s in re.split(r"(?<=[.!?])\s+", p.strip()) if s.strip()])
            for p in paragraphs
        ]
        if statistics.mean(sentences_per_paragraph) > 0:
            cv = statistics.stdev(sentences_per_paragraph) / statistics.mean(sentences_per_paragraph)
            structure_score = _clamp(1 - cv)
        else:
            structure_score = 0.5
    else:
        structure_score = 0.5  # single paragraph: not enough structure to measure

    metrics = {
        "sentence_variance_score": sentence_variance_score,
        "ttr_score": ttr_score,
        "punct_score": punct_score,
        "word_len_score": word_len_score,
        "structure_score": structure_score,
    }

    stylo_score = sum(metrics.values()) / len(metrics)

    return {"stylo_score": stylo_score, "metrics": metrics}


_GENERIC_CAPTION_PHRASES = [
    r"a photo of", r"an image of", r"a picture of", r"this image shows",
    r"this photo shows", r"depicting", r"featuring", r"in this image",
    r"a photograph of", r"showing a", r"showing an",
]


def caption_signal(text):
    # Tailored for short image-caption/alt-text strings rather than prose:
    # AI-generated captions lean on generic templated openers and rarely
    # name specific entities, counts, or proper nouns the way a human
    # describing their own photo would.
    words = re.findall(r"[A-Za-z']+", text)
    lower = text.lower()

    # 1. Generic opener phrases: AI captions overwhelmingly start this way.
    generic_hits = sum(1 for phrase in _GENERIC_CAPTION_PHRASES if re.search(phrase, lower))
    generic_score = _clamp(generic_hits / 2)  # 2+ hits already maxes the score

    # 2. Specificity: proper nouns (capitalized mid-string) and digits suggest
    # a human naming a real place, person, or count. Their absence = AI-like.
    proper_nouns = re.findall(r"(?<!^)(?<![.!?]\s)\b[A-Z][a-z]+", text)
    digits = re.findall(r"\d+", text)
    specificity_hits = len(proper_nouns) + len(digits)
    specificity_score = _clamp(1 - min(specificity_hits / 2, 1))

    # 3. Length: AI captions cluster in a narrow mid-length band; very short
    # or very long captions are more often human-written (terse or rambling).
    word_count = len(words)
    if 6 <= word_count <= 20:
        length_score = 0.7
    else:
        length_score = 0.3

    metrics = {
        "generic_phrase_score": generic_score,
        "specificity_score": specificity_score,
        "length_score": length_score,
    }

    caption_score = sum(metrics.values()) / len(metrics)

    return {"caption_score": caption_score, "metrics": metrics}


if __name__ == "__main__":
    test_inputs = [
        "In conclusion, it is important to note that the aforementioned factors collectively "
        "contribute to a comprehensive understanding of the subject matter at hand. "
        "Furthermore, these considerations underscore the significance of a balanced approach.",
        "honestly idk why but today just felt off, like i woke up and my coffee tasted "
        "weird and then i missed the bus and just spent the whole day kind of annoyed lol",
        "The cat sat on the windowsill, tail flicking, watching rain streak down the glass.",
    ]

    for text in test_inputs:
        print(text[:60] + "...")
        print("llm:  ", llm_signal(text))
        print("stylo:", stylo_signal(text))
        print()
